### ISSUE TITLE
Is there a way to save html using note's title?

### ISSUE THREAD

**Issue by callzhang** [dunhamsteve/notesutils#1]
Current way of naming it with UUID isn't very friendly when trying to find a file in hundreds of exported notes. Is there a way to save html using note's title?

**Comment by callzhang** [comment]
PR created: #2

**Comment by dunhamsteve** [comment]
I've taken a slightly different approach to this.  There is now an optional command line flag `--title` that will use Apple's guess at the title (found in the ZTITLE1 column of the database) for the filename. I also add _1, _2, etc to the title in the case of duplicates.
